### ISSUE TITLE
emails the administrator changing the role, rather than the user who's role is being changed

### ISSUE THREAD

**Issue by alexlancaster** [MissVeronica/UM-Role-is-changed-email#1]
Hi there,

I am using Ultimate Member 2.3.1 on WordPress (WordPress 5.9.2 / PHP version: 7.4.28) and I have followed the instructions here and downloaded the PHP code for this feature (Version 1.1 2022-01-17) and enabled it using the "code snippets" plugin.  It installs fine and appear as a new custom template in the "Email" tab in the UM settings.  It also sends email upon role changes, unfortunately it appears to be sending the emails to the user that is doing the role change, rather that the user whose role is being changed. 

In addition, using the email template you provided, it picks up the `{site_name}` correctly but does not map `{old_role}` or `{role}`  and the `{display_name}`, as mentioned above the name of the user doing the role changing, so the emails look like this:

> Hello Username
> 
> Your Role at our site My Site Name has been changed from {old_role} to {role}

I'm wondering if this mght have something do with the user doing the role changes being a default WordPress `Administrator` not a user with the UM `um_admin` role?  

Any hints are welcome.  Thanks!

**Comment by MissVeronica** [comment]
Hi,
Now you can download an updated version of this code snippet.

Fixes: 
{role} {old_role} now replaced in the email body text.
{display_name} replaced before UM doing the replacement.

**Comment by alexlancaster** [comment]
Great - that fixes the user name problem.  Thank you! I didn't notice that it was actually sending it to the correct email addresses (since they were all aliases that got sent to me during testing).   However:

> {role} {old_role} now replaced in the email body text.

seems to work for the body of the email, but not in the Subject line, in the UM UI I set it to:

>  {site_name} | {display_name} your sign-up is complete and you are now a {role}

but the email comes back again with the administrator name and doesn't substitute `{role}`

> SiteName | Administrator your sign-up is complete and you are now a {role}

**Comment by MissVeronica** [comment]
Fix:
Placeholder replacements included for the Email Subject.
Rewrite of the "custom_role_is_changed_email" function.

**Comment by alexlancaster** [comment]
Great, thanks!  Seems to all be working now!  Closing issue.
